
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author dorki
 */
public class Szinhaz extends javax.swing.JFrame {

    int jegyAlapAr = -1;
    int db, eloadasAra, eloadas, darabszorzo;
    double vegsoAr;

    /**
     * Creates new form Szinhaz
     */
    public Szinhaz() {
        initComponents();
        jegyAlapAr = 0;
        
     
         eloadasSzamitasa();

        db = 1;

        szamitasEsKiiras();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        chbBab = new javax.swing.JCheckBox();
        chbDrama = new javax.swing.JCheckBox();
        chbOpera = new javax.swing.JCheckBox();
        chbBalett = new javax.swing.JCheckBox();
        chbMusical = new javax.swing.JCheckBox();
        chbKomedia = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblFizdb = new javax.swing.JLabel();
        numDb = new javax.swing.JSpinner();
        lblAr = new javax.swing.JLabel();
        lblFizFt = new javax.swing.JLabel();
        cmbValaszthatoJegyek = new javax.swing.JComboBox<>();
        btnInfo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        chbHarom = new javax.swing.JCheckBox();
        chbFiuk = new javax.swing.JCheckBox();
        chbGatsby = new javax.swing.JCheckBox();
        chbDiotoro = new javax.swing.JCheckBox();
        chbVarazsfuvola = new javax.swing.JCheckBox();
        chbJuan = new javax.swing.JCheckBox();
        chbRomeo = new javax.swing.JCheckBox();
        chbCsongor = new javax.swing.JCheckBox();
        chbEmber = new javax.swing.JCheckBox();
        chbHegedus = new javax.swing.JCheckBox();
        chbIstvan = new javax.swing.JCheckBox();
        chbAlom = new javax.swing.JCheckBox();
        chbHolle = new javax.swing.JCheckBox();
        chbKrum = new javax.swing.JCheckBox();
        chbNap = new javax.swing.JCheckBox();
        chbBarany = new javax.swing.JCheckBox();
        chbGengszter = new javax.swing.JCheckBox();
        chbHattyuk = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnMegse = new javax.swing.JButton();
        btnVesz = new javax.swing.JButton();
        chbErtesites = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Színház");

        jPanel6.setBackground(new java.awt.Color(225, 202, 232));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Kategóriák"));

        buttonGroup1.add(chbBab);
        chbBab.setText("Bábjáték");
        chbBab.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbBabItemStateChanged(evt);
            }
        });

        buttonGroup1.add(chbDrama);
        chbDrama.setText("Dráma");
        chbDrama.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbDramaItemStateChanged(evt);
            }
        });

        buttonGroup1.add(chbOpera);
        chbOpera.setText("Opera");
        chbOpera.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbOperaItemStateChanged(evt);
            }
        });

        buttonGroup1.add(chbBalett);
        chbBalett.setText("Balett");
        chbBalett.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbBalettItemStateChanged(evt);
            }
        });

        buttonGroup1.add(chbMusical);
        chbMusical.setText("Musical");
        chbMusical.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbMusicalItemStateChanged(evt);
            }
        });

        buttonGroup1.add(chbKomedia);
        chbKomedia.setText("Komédia");
        chbKomedia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbKomediaItemStateChanged(evt);
            }
        });

        jTextField2.setText("Kérem válasszon kategóriát!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(chbDrama, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chbMusical, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chbKomedia, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbBalett, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbOpera, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbBab, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbOpera)
                    .addComponent(chbKomedia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbDrama)
                    .addComponent(chbBalett))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbMusical)
                    .addComponent(chbBab))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jegyek"));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Fizetendő"));

        lblFizdb.setText("db:");

        numDb.setModel(new javax.swing.SpinnerNumberModel(1, 0, 20, 1));
        numDb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numDbStateChanged(evt);
            }
        });

        lblAr.setText("   0");

        lblFizFt.setText("Ft");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblAr, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFizFt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblFizdb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numDb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAr)
                    .addComponent(lblFizFt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFizdb)
                    .addComponent(numDb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmbValaszthatoJegyek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kérem válasszon jegyet!", "Diák", "Gyerek", "Felnőtt", "Kedvezményes", "Családi", "Páros", "Csoportos" }));
        cmbValaszthatoJegyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbValaszthatoJegyekActionPerformed(evt);
            }
        });

        btnInfo.setText("Jegy infó");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(cmbValaszthatoJegyek, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(cmbValaszthatoJegyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnInfo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Előadások"));

        chbHarom.setText("Három komédia");
        chbHarom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EloadasokItemStateChanged(evt);
            }
        });

        chbFiuk.setText("A Pál utcai fiúk");

        chbGatsby.setText("A nagy Gatsby");

        chbDiotoro.setText("A Diótörő");

        chbVarazsfuvola.setText("A Varázsfuvola");

        chbJuan.setText("Don Juan");
        chbJuan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EloadasokItemStateChanged(evt);
            }
        });

        chbRomeo.setText("Rómeó és Júlia");

        chbCsongor.setText("Csongor és Tünde");

        chbEmber.setText("Az ember tragédiája");

        chbHegedus.setText("Hegedűs a háztetőn");

        chbIstvan.setText("István, A Király");

        chbAlom.setText("Szentivánéji álom");

        chbHolle.setText("Holle anyó");

        chbKrum.setText("Krum");
        chbKrum.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EloadasokItemStateChanged(evt);
            }
        });

        chbNap.setText(" 80 nap alatt a Föld körül");

        chbBarany.setText("Az utolsó bárány");

        chbGengszter.setText("Gengszter nagyi");

        chbHattyuk.setText("A hattyúk tava");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(chbDiotoro, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chbBarany, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbEmber, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbHattyuk)
                            .addComponent(chbHolle, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbCsongor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbRomeo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbIstvan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbVarazsfuvola, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbNap, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chbGengszter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbAlom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(chbHarom, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chbHegedus))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(chbKrum, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chbGatsby, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(chbJuan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chbFiuk, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(chbGatsby)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbHegedus)
                        .addGap(18, 18, 18)
                        .addComponent(chbVarazsfuvola)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbJuan)
                            .addComponent(chbFiuk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbKrum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbHarom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbRomeo)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(chbIstvan))
                    .addComponent(chbCsongor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbAlom)
                    .addComponent(chbEmber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbDiotoro)
                    .addComponent(chbBarany))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbHolle)
                    .addComponent(chbGengszter, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbNap)
                    .addComponent(chbHattyuk))
                .addGap(41, 41, 41))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Összesítő"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Drama_maszk.png"))); // NOI18N

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(226, 184, 46));
        jLabel1.setText(" Színházi Káprázat");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        btnMegse.setText("Mégse");
        btnMegse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegseActionPerformed(evt);
            }
        });

        btnVesz.setText("Megveszem");
        btnVesz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeszActionPerformed(evt);
            }
        });

        chbErtesites.setText("Szeretnék értesítést kapni ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnVesz, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnMegse, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(chbErtesites, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMegse, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVesz, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chbErtesites)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 3, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 33, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chbDramaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbDramaItemStateChanged
        if (chbDrama.isSelected()) {
            chbHarom.setEnabled(false);
            chbJuan.setEnabled(false);
            chbKrum.setEnabled(false);
            chbDiotoro.setEnabled(false);
            chbHolle.setEnabled(false);
            chbHattyuk.setEnabled(false);
            chbFiuk.setEnabled(false);
            chbGatsby.setEnabled(false);
            chbHegedus.setEnabled(false);
            chbVarazsfuvola.setEnabled(false);
            chbIstvan.setEnabled(false);
            chbAlom.setEnabled(false);
            chbBarany.setEnabled(false);
            chbGengszter.setEnabled(false);
            chbNap.setEnabled(false);

        } else {
            chbHarom.setEnabled(true);
            chbJuan.setEnabled(true);
            chbKrum.setEnabled(true);
            chbDiotoro.setEnabled(true);
            chbHolle.setEnabled(true);
            chbHattyuk.setEnabled(true);
            chbFiuk.setEnabled(true);
            chbGatsby.setEnabled(true);
            chbHegedus.setEnabled(true);
            chbVarazsfuvola.setEnabled(true);
            chbIstvan.setEnabled(true);
            chbAlom.setEnabled(true);
            chbBarany.setEnabled(true);
            chbGengszter.setEnabled(true);
            chbNap.setEnabled(true);
        }
    }//GEN-LAST:event_chbDramaItemStateChanged

    private void chbMusicalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbMusicalItemStateChanged
        if (chbMusical.isSelected()) {
            chbHarom.setEnabled(false);
            chbJuan.setEnabled(false);
            chbKrum.setEnabled(false);
            chbDiotoro.setEnabled(false);
            chbHolle.setEnabled(false);
            chbHattyuk.setEnabled(false);
            chbRomeo.setEnabled(false);
            chbCsongor.setEnabled(false);
            chbEmber.setEnabled(false);
            chbVarazsfuvola.setEnabled(false);
            chbIstvan.setEnabled(false);
            chbAlom.setEnabled(false);
            chbBarany.setEnabled(false);
            chbGengszter.setEnabled(false);
            chbNap.setEnabled(false);

        } else {
            chbHarom.setEnabled(true);
            chbJuan.setEnabled(true);
            chbKrum.setEnabled(true);
            chbDiotoro.setEnabled(true);
            chbHolle.setEnabled(true);
            chbHattyuk.setEnabled(true);
            chbRomeo.setEnabled(true);
            chbCsongor.setEnabled(true);
            chbEmber.setEnabled(true);
            chbVarazsfuvola.setEnabled(true);
            chbIstvan.setEnabled(true);
            chbAlom.setEnabled(true);
            chbBarany.setEnabled(true);
            chbGengszter.setEnabled(true);
            chbNap.setEnabled(true);
        }
    }//GEN-LAST:event_chbMusicalItemStateChanged

    private void chbOperaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbOperaItemStateChanged
        if (chbOpera.isSelected()) {
            chbHarom.setEnabled(false);
            chbJuan.setEnabled(false);
            chbKrum.setEnabled(false);
            chbDiotoro.setEnabled(false);
            chbHolle.setEnabled(false);
            chbHattyuk.setEnabled(false);
            chbFiuk.setEnabled(false);
            chbGatsby.setEnabled(false);
            chbHegedus.setEnabled(false);
            chbCsongor.setEnabled(false);
            chbEmber.setEnabled(false);
            chbRomeo.setEnabled(false);
            chbBarany.setEnabled(false);
            chbGengszter.setEnabled(false);
            chbNap.setEnabled(false);

        } else {
            chbHarom.setEnabled(true);
            chbJuan.setEnabled(true);
            chbKrum.setEnabled(true);
            chbDiotoro.setEnabled(true);
            chbHolle.setEnabled(true);
            chbHattyuk.setEnabled(true);
            chbFiuk.setEnabled(true);
            chbGatsby.setEnabled(true);
            chbHegedus.setEnabled(true);
            chbCsongor.setEnabled(true);
            chbEmber.setEnabled(true);
            chbRomeo.setEnabled(true);
            chbBarany.setEnabled(true);
            chbGengszter.setEnabled(true);
            chbNap.setEnabled(true);
        }
    }//GEN-LAST:event_chbOperaItemStateChanged

    private void chbBalettItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbBalettItemStateChanged
        if (chbBalett.isSelected()) {
            chbHarom.setEnabled(false);
            chbJuan.setEnabled(false);
            chbKrum.setEnabled(false);
            chbRomeo.setEnabled(false);
            chbCsongor.setEnabled(false);
            chbEmber.setEnabled(false);
            chbFiuk.setEnabled(false);
            chbGatsby.setEnabled(false);
            chbHegedus.setEnabled(false);
            chbVarazsfuvola.setEnabled(false);
            chbIstvan.setEnabled(false);
            chbAlom.setEnabled(false);
            chbBarany.setEnabled(false);
            chbGengszter.setEnabled(false);
            chbNap.setEnabled(false);

        } else {
            chbHarom.setEnabled(true);
            chbJuan.setEnabled(true);
            chbKrum.setEnabled(true);
            chbCsongor.setEnabled(true);
            chbEmber.setEnabled(true);
            chbRomeo.setEnabled(true);
            chbFiuk.setEnabled(true);
            chbGatsby.setEnabled(true);
            chbHegedus.setEnabled(true);
            chbVarazsfuvola.setEnabled(true);
            chbIstvan.setEnabled(true);
            chbAlom.setEnabled(true);
            chbBarany.setEnabled(true);
            chbGengszter.setEnabled(true);
            chbNap.setEnabled(true);
        }
    }//GEN-LAST:event_chbBalettItemStateChanged

    private void chbBabItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbBabItemStateChanged
        if (chbBab.isSelected()) {
            chbHarom.setEnabled(false);
            chbJuan.setEnabled(false);
            chbKrum.setEnabled(false);
            chbDiotoro.setEnabled(false);
            chbHolle.setEnabled(false);
            chbHattyuk.setEnabled(false);
            chbFiuk.setEnabled(false);
            chbGatsby.setEnabled(false);
            chbHegedus.setEnabled(false);
            chbVarazsfuvola.setEnabled(false);
            chbIstvan.setEnabled(false);
            chbAlom.setEnabled(false);
            chbRomeo.setEnabled(false);
            chbCsongor.setEnabled(false);
            chbEmber.setEnabled(false);

        } else {
            chbHarom.setEnabled(true);
            chbJuan.setEnabled(true);
            chbKrum.setEnabled(true);
            chbDiotoro.setEnabled(true);
            chbHolle.setEnabled(true);
            chbHattyuk.setEnabled(true);
            chbFiuk.setEnabled(true);
            chbGatsby.setEnabled(true);
            chbHegedus.setEnabled(true);
            chbVarazsfuvola.setEnabled(true);
            chbIstvan.setEnabled(true);
            chbAlom.setEnabled(true);
            chbRomeo.setEnabled(true);
            chbCsongor.setEnabled(true);
            chbEmber.setEnabled(true);
        }
    }//GEN-LAST:event_chbBabItemStateChanged

    private void chbKomediaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbKomediaItemStateChanged
        if (chbKomedia.isSelected()) {
            chbRomeo.setEnabled(false);
            chbCsongor.setEnabled(false);
            chbEmber.setEnabled(false);
            chbDiotoro.setEnabled(false);
            chbHolle.setEnabled(false);
            chbHattyuk.setEnabled(false);
            chbFiuk.setEnabled(false);
            chbGatsby.setEnabled(false);
            chbHegedus.setEnabled(false);
            chbVarazsfuvola.setEnabled(false);
            chbIstvan.setEnabled(false);
            chbAlom.setEnabled(false);
            chbBarany.setEnabled(false);
            chbGengszter.setEnabled(false);
            chbNap.setEnabled(false);

        } else {
            chbRomeo.setEnabled(true);
            chbCsongor.setEnabled(true);
            chbEmber.setEnabled(true);
            chbDiotoro.setEnabled(true);
            chbHolle.setEnabled(true);
            chbHattyuk.setEnabled(true);
            chbFiuk.setEnabled(true);
            chbGatsby.setEnabled(true);
            chbHegedus.setEnabled(true);
            chbVarazsfuvola.setEnabled(true);
            chbIstvan.setEnabled(true);
            chbAlom.setEnabled(true);
            chbBarany.setEnabled(true);
            chbGengszter.setEnabled(true);
            chbNap.setEnabled(true);
        }
    }//GEN-LAST:event_chbKomediaItemStateChanged

    private void cmbValaszthatoJegyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbValaszthatoJegyekActionPerformed
        int jegyIndex = cmbValaszthatoJegyek.getSelectedIndex();

        if (jegyIndex == 0) {
            jegyAlapAr = 0;
        } else if (jegyIndex == 1) {   //Diák//
            jegyAlapAr = 3500;

        } else if (jegyIndex == 2) {  //Gyerek//
            jegyAlapAr = 3000;

        } else if (jegyIndex == 3) {   //Felnőtt//
            jegyAlapAr = 4000;

        } else if (jegyIndex == 4) {   //Kedvezményes//
            jegyAlapAr = 2500;
            
        } else if (jegyIndex == 5) {   //Családi
            jegyAlapAr = 12000;
            
        } else if (jegyIndex == 6) {   //Páros
            jegyAlapAr = 6000;
        
        } else if (jegyIndex == 7) {   //Csoportos
            jegyAlapAr = 16000;
        }
        eloadasSzamitasa();

        db = 1;

        szamitasEsKiiras();


    }//GEN-LAST:event_cmbValaszthatoJegyekActionPerformed

    private void numDbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numDbStateChanged
        db = (int) numDb.getValue();
        szamitasEsKiiras();
    }//GEN-LAST:event_numDbStateChanged

    private void btnVeszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeszActionPerformed
        String sep = System.lineSeparator();
        String jegy = (String)cmbValaszthatoJegyek.getSelectedItem();
        String kimenet = "A választott jegy : " + jegy;
        
        kimenet += String.format(" (%d db)%s", db, sep);
        
              String kategoria = null;
          if(chbKomedia.isSelected()){
            kategoria = chbKomedia.getText();
          
          if(chbDrama.isSelected()){
           kategoria = chbDrama.getText();
                  }
          else if (chbMusical.isSelected()){
            kategoria = chbMusical.getText();
          }
           else if (chbOpera.isSelected()){
          kategoria = chbOpera.getText();
                  }
          else if (chbBalett.isSelected()){
          kategoria = chbBalett.getText();
                  }
          else if (chbBab.isSelected()){
          kategoria = chbBab.getText();
                  }     
        }else{
           
          }
        kimenet += "kategória: " + kategoria;
        kimenet += sep; 
        kimenet += "jegyek: " +sep;
    }//GEN-LAST:event_btnVeszActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Kedvezményes:"+System.lineSeparator()+"-Fogyatékkal élők"+System.lineSeparator()+"-65 év felettiek"+System.lineSeparator()+
                "Családi: 2 Felnőtt és 2 Gyerek"+System.lineSeparator()+"Páros: 2 Felnőtt"+System.lineSeparator()+"Csoportos: 5 Fő");
        
    }//GEN-LAST:event_btnInfoActionPerformed

    private void EloadasokItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EloadasokItemStateChanged
        JCheckBox chb = (JCheckBox)evt.getSource();
        int eloadasAra = 1500;

        if (chb.isSelected()) {
            eloadas += eloadasAra;
        } else {
            eloadas -= eloadasAra;
        }

        szamitasEsKiiras();


    }//GEN-LAST:event_EloadasokItemStateChanged

    private void btnMegseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegseActionPerformed
         System.exit(0);
    }//GEN-LAST:event_btnMegseActionPerformed
   // private void EloadasokItemStateChanged(java.awt.event.ItemEvent evt) {
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Szinhaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Szinhaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Szinhaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Szinhaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Szinhaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnMegse;
    private javax.swing.JButton btnVesz;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JCheckBox chbAlom;
    private javax.swing.JCheckBox chbBab;
    private javax.swing.JCheckBox chbBalett;
    private javax.swing.JCheckBox chbBarany;
    private javax.swing.JCheckBox chbCsongor;
    private javax.swing.JCheckBox chbDiotoro;
    private javax.swing.JCheckBox chbDrama;
    private javax.swing.JCheckBox chbEmber;
    private javax.swing.JCheckBox chbErtesites;
    private javax.swing.JCheckBox chbFiuk;
    private javax.swing.JCheckBox chbGatsby;
    private javax.swing.JCheckBox chbGengszter;
    private javax.swing.JCheckBox chbHarom;
    private javax.swing.JCheckBox chbHattyuk;
    private javax.swing.JCheckBox chbHegedus;
    private javax.swing.JCheckBox chbHolle;
    private javax.swing.JCheckBox chbIstvan;
    private javax.swing.JCheckBox chbJuan;
    private javax.swing.JCheckBox chbKomedia;
    private javax.swing.JCheckBox chbKrum;
    private javax.swing.JCheckBox chbMusical;
    private javax.swing.JCheckBox chbNap;
    private javax.swing.JCheckBox chbOpera;
    private javax.swing.JCheckBox chbRomeo;
    private javax.swing.JCheckBox chbVarazsfuvola;
    private javax.swing.JComboBox<String> cmbValaszthatoJegyek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblAr;
    private javax.swing.JLabel lblFizFt;
    private javax.swing.JLabel lblFizdb;
    private javax.swing.JSpinner numDb;
    // End of variables declaration//GEN-END:variables

    private void szamitasEsKiiras() {
        int darabszorzo = 0;
        vegsoAr = jegyAlapAr + eloadasAra;
        vegsoAr *= db; //vegsoAr = vegsoAr * db;

        lblAr.setText(vegsoAr + "");
        
    }

    private void eloadasSzamitasa() {
        int eloadas1 = 100;
        int eloadas2 = 0;
        int eloadas3 = 0;
        int eloadas4 = 0;
        int eloadas5 = 0;
        int eloadas6 = 0;
        int eloadas7 = 0;
        int eloadas8 = 0;
        int eloadas9 = 0;
        int eloadas10 = 0;
        int eloadas11 = 0;
        int eloadas12 = 0;
        int eloadas13 = 0;
        int eloadas14 = 0;
        int eloadas15 = 0;
        int eloadas16 = 0;
        int eloadas17 = 0;
        int eloadas18 = 0;
        
        eloadas = eloadas1 + eloadas2 + eloadas3 + eloadas4 + eloadas5 
                +eloadas6 + eloadas7 + eloadas8 + eloadas9 + eloadas10
                +eloadas11 +eloadas12 +eloadas13 +eloadas14 +eloadas15
                +eloadas16 +eloadas17 +eloadas18;
}
}
