
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author dorki
 */
public class Szinhaz extends javax.swing.JFrame {

    int jegyAlapAr = -1;
    int db,kategoriak, eloadas, darabszorzo;
    double vegsoAr;
    int raszamolas = 1500;

    /**
     * Creates new form Szinhaz
     */
    public Szinhaz() {
        initComponents();
        jegyAlapAr = 0;
        
        darabszorzo = 1;
       
        db = 1;

        szamitasEsKiiras();
    }

  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        chbBab = new javax.swing.JCheckBox();
        chbDrama = new javax.swing.JCheckBox();
        chbOpera = new javax.swing.JCheckBox();
        chbBalett = new javax.swing.JCheckBox();
        chbMusical = new javax.swing.JCheckBox();
        chbKomedia = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        chbHarom = new javax.swing.JCheckBox();
        chbFiuk = new javax.swing.JCheckBox();
        chbGatsby = new javax.swing.JCheckBox();
        chbDiotoro = new javax.swing.JCheckBox();
        chbVarazsfuvola = new javax.swing.JCheckBox();
        chbJuan = new javax.swing.JCheckBox();
        chbRomeo = new javax.swing.JCheckBox();
        chbCsongor = new javax.swing.JCheckBox();
        chbEmber = new javax.swing.JCheckBox();
        chbHegedus = new javax.swing.JCheckBox();
        chbIstvan = new javax.swing.JCheckBox();
        chbAlom = new javax.swing.JCheckBox();
        chbHolle = new javax.swing.JCheckBox();
        chbKrum = new javax.swing.JCheckBox();
        chbNap = new javax.swing.JCheckBox();
        chbBarany = new javax.swing.JCheckBox();
        chbGengszter = new javax.swing.JCheckBox();
        chbHattyuk = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblFizdb = new javax.swing.JLabel();
        numDb = new javax.swing.JSpinner();
        lblAr = new javax.swing.JLabel();
        lblFizFt = new javax.swing.JLabel();
        cmbValaszthatoJegyek = new javax.swing.JComboBox<>();
        btnInfo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaOsszesito = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnMegse = new javax.swing.JButton();
        btnVesz = new javax.swing.JButton();
        chbErtesites = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Színház");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(900, 800));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(226, 184, 46)));

        buttonGroup1.add(chbBab);
        chbBab.setText("Bábjáték");
        chbBab.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbBabItemStateChanged(evt);
            }
        });

        buttonGroup1.add(chbDrama);
        chbDrama.setText("Dráma");
        chbDrama.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbDramaItemStateChanged(evt);
            }
        });

        buttonGroup1.add(chbOpera);
        chbOpera.setText("Opera");
        chbOpera.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbOperaItemStateChanged(evt);
            }
        });

        buttonGroup1.add(chbBalett);
        chbBalett.setText("Balett");
        chbBalett.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbBalettItemStateChanged(evt);
            }
        });

        buttonGroup1.add(chbMusical);
        chbMusical.setText("Musical");
        chbMusical.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbMusicalItemStateChanged(evt);
            }
        });

        buttonGroup1.add(chbKomedia);
        chbKomedia.setText("Komédia");
        chbKomedia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbKomediaItemStateChanged(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField2.setText("Kérem válasszon kategóriát!");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(226, 184, 46)));

        chbHarom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbHarom.setText("Három komédia");

        chbFiuk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbFiuk.setText("A Pál utcai fiúk");

        chbGatsby.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbGatsby.setText("A nagy Gatsby");

        chbDiotoro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbDiotoro.setText("A Diótörő");

        chbVarazsfuvola.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbVarazsfuvola.setText("A Varázsfuvola");

        chbJuan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbJuan.setText("Don Juan");

        chbRomeo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbRomeo.setText("Rómeó és Júlia");

        chbCsongor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbCsongor.setText("Csongor és Tünde");

        chbEmber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbEmber.setText("Az ember tragédiája");

        chbHegedus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbHegedus.setText("Hegedűs a háztetőn");

        chbIstvan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbIstvan.setText("István, A Király");

        chbAlom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbAlom.setText("Szentivánéji álom");

        chbHolle.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbHolle.setText("Holle anyó");

        chbKrum.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbKrum.setText("Krum");

        chbNap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbNap.setText(" 80 nap alatt a Föld körül");

        chbBarany.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbBarany.setText("Az utolsó bárány");

        chbGengszter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbGengszter.setText("Gengszter nagyi");

        chbHattyuk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbHattyuk.setText("A hattyúk tava");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("Előadás");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(chbJuan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chbFiuk, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chbEmber, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chbHattyuk)
                                            .addComponent(chbHolle, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chbCsongor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chbRomeo))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chbVarazsfuvola, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chbIstvan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chbAlom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chbGengszter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chbNap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(chbDiotoro, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chbBarany, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chbKrum, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chbHarom, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chbGatsby, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chbHegedus, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbFiuk)
                            .addComponent(chbJuan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbGatsby)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbHegedus)
                        .addGap(18, 18, 18)
                        .addComponent(chbVarazsfuvola)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(chbKrum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbHarom, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chbRomeo)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbIstvan)
                    .addComponent(chbCsongor))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbEmber)
                    .addComponent(chbAlom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbDiotoro)
                    .addComponent(chbBarany))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbHolle)
                    .addComponent(chbGengszter, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbNap)
                    .addComponent(chbHattyuk))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chbDrama, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chbMusical, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(126, 126, 126)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chbBalett, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chbBab, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chbKomedia, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(chbOpera, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbOpera)
                    .addComponent(chbKomedia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbDrama)
                    .addComponent(chbBalett))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbMusical)
                    .addComponent(chbBab))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(226, 184, 46)));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fizetendő", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N

        lblFizdb.setText("db:");
        lblFizdb.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblFizdbInputMethodTextChanged(evt);
            }
        });

        numDb.setModel(new javax.swing.SpinnerNumberModel(1, 0, 20, 1));
        numDb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numDbStateChanged(evt);
            }
        });

        lblAr.setText("   0");

        lblFizFt.setText("Ft");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblAr, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFizFt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblFizdb)
                        .addGap(18, 18, 18)
                        .addComponent(numDb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAr)
                    .addComponent(lblFizFt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFizdb)
                    .addComponent(numDb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmbValaszthatoJegyek.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        cmbValaszthatoJegyek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kérem válasszon jegyet!", "Diák", "Gyerek", "Felnőtt", "Kedvezményes", "Családi", "Páros", "Csoportos" }));
        cmbValaszthatoJegyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbValaszthatoJegyekActionPerformed(evt);
            }
        });

        btnInfo.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnInfo.setText("Jegy infó");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbValaszthatoJegyek, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cmbValaszthatoJegyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(226, 184, 46)), "Összesítő", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N

        txaOsszesito.setColumns(20);
        txaOsszesito.setRows(5);
        jScrollPane1.setViewportView(txaOsszesito);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(226, 184, 46));
        jLabel1.setText(" Színházi Káprázat");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        btnMegse.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnMegse.setText("Mégse");
        btnMegse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegseActionPerformed(evt);
            }
        });

        btnVesz.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnVesz.setText("Megveszem");
        btnVesz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeszActionPerformed(evt);
            }
        });

        chbErtesites.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chbErtesites.setSelected(true);
        chbErtesites.setText("Szeretnék értesítést kapni a további informáciokról");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbErtesites, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnVesz, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMegse, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMegse, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVesz, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chbErtesites, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Drama_maszk1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(94, 94, 94))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chbDramaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbDramaItemStateChanged
        if (chbDrama.isSelected()) {
            chbHarom.setEnabled(false);
            chbJuan.setEnabled(false);
            chbKrum.setEnabled(false);
            chbDiotoro.setEnabled(false);
            chbHolle.setEnabled(false);
            chbHattyuk.setEnabled(false);
            chbFiuk.setEnabled(false);
            chbGatsby.setEnabled(false);
            chbHegedus.setEnabled(false);
            chbVarazsfuvola.setEnabled(false);
            chbIstvan.setEnabled(false);
            chbAlom.setEnabled(false);
            chbBarany.setEnabled(false);
            chbGengszter.setEnabled(false);
            chbNap.setEnabled(false);

        } else {
            chbHarom.setEnabled(true);
            chbJuan.setEnabled(true);
            chbKrum.setEnabled(true);
            chbDiotoro.setEnabled(true);
            chbHolle.setEnabled(true);
            chbHattyuk.setEnabled(true);
            chbFiuk.setEnabled(true);
            chbGatsby.setEnabled(true);
            chbHegedus.setEnabled(true);
            chbVarazsfuvola.setEnabled(true);
            chbIstvan.setEnabled(true);
            chbAlom.setEnabled(true);
            chbBarany.setEnabled(true);
            chbGengszter.setEnabled(true);
            chbNap.setEnabled(true);
        }
    }//GEN-LAST:event_chbDramaItemStateChanged

    private void chbMusicalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbMusicalItemStateChanged
        if (chbMusical.isSelected()) {
            chbHarom.setEnabled(false);
            chbJuan.setEnabled(false);
            chbKrum.setEnabled(false);
            chbDiotoro.setEnabled(false);
            chbHolle.setEnabled(false);
            chbHattyuk.setEnabled(false);
            chbRomeo.setEnabled(false);
            chbCsongor.setEnabled(false);
            chbEmber.setEnabled(false);
            chbVarazsfuvola.setEnabled(false);
            chbIstvan.setEnabled(false);
            chbAlom.setEnabled(false);
            chbBarany.setEnabled(false);
            chbGengszter.setEnabled(false);
            chbNap.setEnabled(false);

        } else {
            chbHarom.setEnabled(true);
            chbJuan.setEnabled(true);
            chbKrum.setEnabled(true);
            chbDiotoro.setEnabled(true);
            chbHolle.setEnabled(true);
            chbHattyuk.setEnabled(true);
            chbRomeo.setEnabled(true);
            chbCsongor.setEnabled(true);
            chbEmber.setEnabled(true);
            chbVarazsfuvola.setEnabled(true);
            chbIstvan.setEnabled(true);
            chbAlom.setEnabled(true);
            chbBarany.setEnabled(true);
            chbGengszter.setEnabled(true);
            chbNap.setEnabled(true);
        }
    }//GEN-LAST:event_chbMusicalItemStateChanged

    private void chbOperaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbOperaItemStateChanged
         if (chbOpera.isSelected()) {
            chbHarom.setEnabled(false);
            chbJuan.setEnabled(false);
            chbKrum.setEnabled(false);
            chbDiotoro.setEnabled(false);
            chbHolle.setEnabled(false);
            chbHattyuk.setEnabled(false);
            chbFiuk.setEnabled(false);
            chbGatsby.setEnabled(false);
            chbHegedus.setEnabled(false);
            chbCsongor.setEnabled(false);
            chbEmber.setEnabled(false);
            chbRomeo.setEnabled(false);
            chbBarany.setEnabled(false);
            chbGengszter.setEnabled(false);
            chbNap.setEnabled(false);

        } else {
            chbHarom.setEnabled(true);
            chbJuan.setEnabled(true);
            chbKrum.setEnabled(true);
            chbDiotoro.setEnabled(true);
            chbHolle.setEnabled(true);
            chbHattyuk.setEnabled(true);
            chbFiuk.setEnabled(true);
            chbGatsby.setEnabled(true);
            chbHegedus.setEnabled(true);
            chbCsongor.setEnabled(true);
            chbEmber.setEnabled(true);
            chbRomeo.setEnabled(true);
            chbBarany.setEnabled(true);
            chbGengszter.setEnabled(true);
            chbNap.setEnabled(true);
        }
    }//GEN-LAST:event_chbOperaItemStateChanged

    private void chbBalettItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbBalettItemStateChanged
        if (chbBalett.isSelected()) {
            chbHarom.setEnabled(false);
            chbJuan.setEnabled(false);
            chbKrum.setEnabled(false);
            chbRomeo.setEnabled(false);
            chbCsongor.setEnabled(false);
            chbEmber.setEnabled(false);
            chbFiuk.setEnabled(false);
            chbGatsby.setEnabled(false);
            chbHegedus.setEnabled(false);
            chbVarazsfuvola.setEnabled(false);
            chbIstvan.setEnabled(false);
            chbAlom.setEnabled(false);
            chbBarany.setEnabled(false);
            chbGengszter.setEnabled(false);
            chbNap.setEnabled(false);

        } else {
            chbHarom.setEnabled(true);
            chbJuan.setEnabled(true);
            chbKrum.setEnabled(true);
            chbCsongor.setEnabled(true);
            chbEmber.setEnabled(true);
            chbRomeo.setEnabled(true);
            chbFiuk.setEnabled(true);
            chbGatsby.setEnabled(true);
            chbHegedus.setEnabled(true);
            chbVarazsfuvola.setEnabled(true);
            chbIstvan.setEnabled(true);
            chbAlom.setEnabled(true);
            chbBarany.setEnabled(true);
            chbGengszter.setEnabled(true);
            chbNap.setEnabled(true);
        }
    }//GEN-LAST:event_chbBalettItemStateChanged

    private void chbBabItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbBabItemStateChanged
        if (chbBab.isSelected()) {
            chbHarom.setEnabled(false);
            chbJuan.setEnabled(false);
            chbKrum.setEnabled(false);
            chbDiotoro.setEnabled(false);
            chbHolle.setEnabled(false);
            chbHattyuk.setEnabled(false);
            chbFiuk.setEnabled(false);
            chbGatsby.setEnabled(false);
            chbHegedus.setEnabled(false);
            chbVarazsfuvola.setEnabled(false);
            chbIstvan.setEnabled(false);
            chbAlom.setEnabled(false);
            chbRomeo.setEnabled(false);
            chbCsongor.setEnabled(false);
            chbEmber.setEnabled(false);

        } else {
            chbHarom.setEnabled(true);
            chbJuan.setEnabled(true);
            chbKrum.setEnabled(true);
            chbDiotoro.setEnabled(true);
            chbHolle.setEnabled(true);
            chbHattyuk.setEnabled(true);
            chbFiuk.setEnabled(true);
            chbGatsby.setEnabled(true);
            chbHegedus.setEnabled(true);
            chbVarazsfuvola.setEnabled(true);
            chbIstvan.setEnabled(true);
            chbAlom.setEnabled(true);
            chbRomeo.setEnabled(true);
            chbCsongor.setEnabled(true);
            chbEmber.setEnabled(true);
        }
    }//GEN-LAST:event_chbBabItemStateChanged

    private void chbKomediaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbKomediaItemStateChanged
        if (chbKomedia.isSelected()) {
            chbRomeo.setEnabled(false);
            chbCsongor.setEnabled(false);
            chbEmber.setEnabled(false);
            chbDiotoro.setEnabled(false);
            chbHolle.setEnabled(false);
            chbHattyuk.setEnabled(false);
            chbFiuk.setEnabled(false);
            chbGatsby.setEnabled(false);
            chbHegedus.setEnabled(false);
            chbVarazsfuvola.setEnabled(false);
            chbIstvan.setEnabled(false);
            chbAlom.setEnabled(false);
            chbBarany.setEnabled(false);
            chbGengszter.setEnabled(false);
            chbNap.setEnabled(false);

        } else {
            chbRomeo.setEnabled(true);
            chbCsongor.setEnabled(true);
            chbEmber.setEnabled(true);
            chbDiotoro.setEnabled(true);
            chbHolle.setEnabled(true);
            chbHattyuk.setEnabled(true);
            chbFiuk.setEnabled(true);
            chbGatsby.setEnabled(true);
            chbHegedus.setEnabled(true);
            chbVarazsfuvola.setEnabled(true);
            chbIstvan.setEnabled(true);
            chbAlom.setEnabled(true);
            chbBarany.setEnabled(true);
            chbGengszter.setEnabled(true);
            chbNap.setEnabled(true);
        }
    }//GEN-LAST:event_chbKomediaItemStateChanged

    private void cmbValaszthatoJegyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbValaszthatoJegyekActionPerformed
        int jegyIndex = cmbValaszthatoJegyek.getSelectedIndex();
 
        if(jegyIndex == 0){ 
            jegyAlapAr = 0;
        }else if(jegyIndex == 1){ //Diák
            jegyAlapAr = 3500;
        }else if(jegyIndex == 2){ //Gyerek
            jegyAlapAr = 3000;
        }else if(jegyIndex == 3){ //Felnőtt
             jegyAlapAr = 4000;
        }else if(jegyIndex == 4){ //Kedvezményes
             jegyAlapAr = 2500;
        }else if(jegyIndex == 5){ //Családi
             jegyAlapAr = 13000;
        }else if(jegyIndex == 6){ //Páros
             jegyAlapAr = 6000;
        }else if(jegyIndex == 7){ //Csoportos
             jegyAlapAr = 16000;
        }
        
        
        int kategoria1 = 0;
        int kategoria2 = 0;
        int kategoria3 = 0;
        int kategoria4 = 0;
        int kategoria5 = 0;
        int kategoria6 = 0;
       kategoriak = kategoria1 + kategoria2 + kategoria3
               + kategoria4 +kategoria5 +kategoria6;
       db= 1;
        szamitasEsKiiras();
    }//GEN-LAST:event_cmbValaszthatoJegyekActionPerformed

    private void numDbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numDbStateChanged
        db = (int) numDb.getValue();
        szamitasEsKiiras();
    }//GEN-LAST:event_numDbStateChanged

    private void btnVeszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeszActionPerformed
       String sep = System.lineSeparator();
        
        String jegy = (String)cmbValaszthatoJegyek.getSelectedItem();
        String kimenet = "A választott jegy : " + jegy;
 
        kimenet += String.format(" (%d db)%s", db, sep);
       
        String kategoria = null;
        if(chbKomedia.isSelected()){
           kategoria = chbKomedia.getText();
           
        }else if (chbDrama.isSelected()){
            kategoria = chbDrama.getText();
            
        }else if (chbMusical.isSelected()){
            kategoria = chbMusical.getText();
            
        }else if (chbOpera.isSelected()){
            kategoria = chbOpera.getText();
            
        }else if (chbBalett.isSelected()){
            kategoria = chbBalett.getText();
            
        }else if (chbBab.isSelected()){
            kategoria = chbBab.getText();
        }
        kimenet += "Kategória: " + kategoria;
        kimenet += sep; 
        
        kimenet += "Előadás: " + sep;
        
        if(chbJuan.isSelected()){
            kimenet += " - Don Juan" + sep;
            kimenet += "Helyszín: Nemzeti Színház" + sep;
            kimenet += "Dátum: 2023.január 4. 19:00" +sep;
        }
        if(chbKrum.isSelected()){
            kimenet += " - Krum" + sep;
            kimenet += "Helyszín: Vígszínház" + sep;
            kimenet += "Dátum: 2023.december 28. 19:00" +sep;
        }
         if(chbHarom.isSelected()){
            kimenet += " - Három Komédia" + sep;
            kimenet += "Helyszín: Madách Színház" + sep;
            kimenet += "Dátum: 2023.január 22. 19:00" +sep;
        }
          if(chbRomeo.isSelected()){
            kimenet += " - Rómeó és Júlia" + sep;  
            kimenet += "Helyszín: Nemzeti Színház" + sep;
            kimenet += "Dátum: 2023.január 12. 17:00" +sep;
        } if(chbCsongor.isSelected()){
            kimenet += " - Csongor és Tünde" + sep;
            kimenet += "Helyszín: Nemzeti Színház" + sep;
            kimenet += "Dátum: 2023.január 10. 17:00" +sep;
        }
         if(chbEmber.isSelected()){
            kimenet += " - Az ember tragédiája" + sep;
            kimenet += "Helyszín: Nemzeti Színház" + sep;
            kimenet += "Dátum: 2024.január 8. 17:00" +sep;
        }
          if(chbDiotoro.isSelected()){
            kimenet += " - A Diótörő" + sep;
            kimenet += "Helyszín: Erkel Színház" + sep;
            kimenet += "Dátum: 2023.december 26. 18:00" +sep;
        }
           if(chbHolle.isSelected()){
            kimenet += " - Holle anyó" + sep;
            kimenet += "Helyszín: Erkel Színház" + sep;
            kimenet += "Dátum: 2023.december 2. 15:00" +sep;
        }
            if(chbHattyuk.isSelected()){
            kimenet += " - A hattyúk tava" + sep;
            kimenet += "Helyszín: Erkel Színház" + sep;
        }
             if(chbFiuk.isSelected()){
            kimenet += " - A pál utcai fiúk" + sep;
            kimenet += "Helyszín: Vígszínház" + sep;
            kimenet += "Dátum: 2023.november 25. 16:00" +sep;
        }
              if(chbGatsby.isSelected()){
            kimenet += " - A nagy Gatsby" + sep;
            kimenet += "Helyszín: Vígszínház" + sep;  
            kimenet += "Dátum: 2023.november 24. 21:00" +sep;
        }
           if(chbHegedus.isSelected()){
            kimenet += " - Hegedűs a háztetőn" + sep;
            kimenet += "Helyszín: Operettszínház" + sep;
            kimenet += "Dátum: 2023.december 21. 19:00" +sep;
            
        }
            if(chbVarazsfuvola.isSelected()){
            kimenet += " - A Varázsfuvola" + sep;
            kimenet += "Helyszín: Operettszínház" + sep;
            kimenet += "Dátum: 2023.november 20. 18:00" +sep;
        }
             if(chbIstvan.isSelected()){
            kimenet += " - István,A király" + sep;
            kimenet += "Helyszín: Operettszínház" + sep;
            kimenet += "Dátum: 2023.november 27. 17:00" +sep;
        }
              if(chbAlom.isSelected()){
            kimenet += " - Szentivánéji álom" + sep;
            kimenet += "Helyszín: Operettszínház" + sep;
            kimenet += "Dátum: 2024.január 6. 20:00" +sep;
        }
               if(chbBarany.isSelected()){
            kimenet += " - Az utolsó bárány" + sep;
            kimenet += "Helyszín: Bábszínház" + sep;
            kimenet += "Dátum: 2023.december 6. 15:00" +sep;
        }
                if(chbGengszter.isSelected()){
            kimenet += " - Gengszter nagyi" + sep;
            kimenet += "Helyszín: Bábszínház" + sep;
            kimenet += "Dátum: 2023.december 12. 18:00" +sep;
        }
           if(chbNap.isSelected()){
            kimenet += " - 80 nap alatt a Föld körül" + sep;
            kimenet += "Helyszín: Bábszínház" + sep;
            kimenet += "Dátum: 2023.március 31. 19:00" +sep;
        }
        
        kimenet += "Rászámolás: " + raszamolas;
        kimenet += sep; 
        if (btnVesz.isSelected()){
            kimenet += "1500Ft" +sep;
        }
      
        txaOsszesito.setText(kimenet);
    }//GEN-LAST:event_btnVeszActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Kedvezményes:"+System.lineSeparator()+"-Fogyatékkal élők"+System.lineSeparator()+"-65 év felettiek"+System.lineSeparator()+
                "Családi: 2 Felnőtt és 2 Gyerek"+System.lineSeparator()+"Páros: 2 Felnőtt"+System.lineSeparator()+"Csoportos: 5 Fő");
        
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnMegseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegseActionPerformed
         System.exit(0);
    }//GEN-LAST:event_btnMegseActionPerformed

    private void lblFizdbInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblFizdbInputMethodTextChanged
       darabszorzo = 1;
       
       szamitasEsKiiras();
    }//GEN-LAST:event_lblFizdbInputMethodTextChanged
   // private void EloadasokItemStateChanged(java.awt.event.ItemEvent evt) {
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Szinhaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Szinhaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Szinhaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Szinhaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Szinhaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnMegse;
    private javax.swing.JButton btnVesz;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JCheckBox chbAlom;
    private javax.swing.JCheckBox chbBab;
    private javax.swing.JCheckBox chbBalett;
    private javax.swing.JCheckBox chbBarany;
    private javax.swing.JCheckBox chbCsongor;
    private javax.swing.JCheckBox chbDiotoro;
    private javax.swing.JCheckBox chbDrama;
    private javax.swing.JCheckBox chbEmber;
    private javax.swing.JCheckBox chbErtesites;
    private javax.swing.JCheckBox chbFiuk;
    private javax.swing.JCheckBox chbGatsby;
    private javax.swing.JCheckBox chbGengszter;
    private javax.swing.JCheckBox chbHarom;
    private javax.swing.JCheckBox chbHattyuk;
    private javax.swing.JCheckBox chbHegedus;
    private javax.swing.JCheckBox chbHolle;
    private javax.swing.JCheckBox chbIstvan;
    private javax.swing.JCheckBox chbJuan;
    private javax.swing.JCheckBox chbKomedia;
    private javax.swing.JCheckBox chbKrum;
    private javax.swing.JCheckBox chbMusical;
    private javax.swing.JCheckBox chbNap;
    private javax.swing.JCheckBox chbOpera;
    private javax.swing.JCheckBox chbRomeo;
    private javax.swing.JCheckBox chbVarazsfuvola;
    private javax.swing.JComboBox<String> cmbValaszthatoJegyek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblAr;
    private javax.swing.JLabel lblFizFt;
    private javax.swing.JLabel lblFizdb;
    private javax.swing.JSpinner numDb;
    private javax.swing.JTextArea txaOsszesito;
    // End of variables declaration//GEN-END:variables

    private void szamitasEsKiiras() {
        vegsoAr = jegyAlapAr * darabszorzo + eloadas + kategoriak + raszamolas;
        vegsoAr *= db; 
        
        lblAr.setText(vegsoAr + "");
        
    }

   

}
